# Configurações do servidor
server.port=8080

# Configurações do MongoDB
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/bd_restaurante?authSource=admin
spring.data.mongodb.database=bd_restaurante
logging.level.org.springframework.security=DEBUG


# URL do servidor Keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8085/realms/meu_reino/protocol/openid-connect/certs


