spring.application.name=restaurante
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/bd_restaurante?authSource=admin

spring.data.mongodb.database=bd_restaurante

api.security.token.secret=your-secret-key

